// 存储一些常量（mutations中函数的函数名）
export const SET_SINGER = 'SET_SINGER';

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE';
export const SET_FULLSCREEN_STATE = 'SET_FULLSCREEN_STATE';
export const SET_PLAYLIST = 'SET_PLAYLIST';
export const SET_SEQUENCELIST = 'SET_SEQUENCELIST';
export const SET_MODE = 'SET_MODE';
export const SET_CURRENTINDEX = 'SET_CURRENTINDEX';

export const SET_RECOMMEND_DESC = 'SET_RECOMMEND_DESC';
export const SET_TOPLIST_DETAIL = 'SET_TOPLIST_DETAIL';
export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';
export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY';
export const SET_LIKE_SONGLIST = 'SET_LIKE_SONGLIST';

export const SET_SCREEN_STATE = 'SET_SCREEN_STATE';
